### ISSUE TITLE
Install SciSpark on your laptop

### ISSUE THREAD

**Issue by wmburke** [SciSpark/Conference#4]
We are aware this will be a frustrating experience. Please file bugs and issues in GitHub and reach out to me with any other questions. As you go, document the process on the wiki.

SciSpark: https://github.com/SciSpark/SciSpark
Report Issues: https://github.com/SciSpark/SciSpark/issues
Document on wiki: https://github.com/SciSpark/SciSpark/wiki (yes, it's empty now!)

**Comment by wmburke** [comment]
@valeriearoth I'm trying to get you added to the team here - and there's some issue (this is the trouble with too much security!). Nonetheless, I wanted you to know that the details are here for you.

Let me know if you have any issues or need some help.

**Comment by valeriearoth** [comment]
Great, thank you! I should have a good amount of time today to make progress on it.
