### ISSUE TITLE
Install SciSpark on JPL-issued laptop

### ISSUE THREAD

**Issue by valeriearoth** [SciSpark/Conference#5]
Follow the new installation instructions that I wrote two weeks ago

**Comment by wmburke** [comment]
+1 - nice!

**Comment by valeriearoth** [comment]
The installation was successful and the instructions have been modified slightly on the SciSpark README.

**Comment by wmburke** [comment]
Cool! Good work, Valerie - and congrats on your instructions working!

**Comment by valeriearoth** [comment]
Thanks Wayne!
