### ISSUE TITLE
Figure out why Zeppelin skin is being cached

### ISSUE THREAD

**Issue by valeriearoth** [SciSpark/Conference#9]
The cache seems to take a really long time to clear, and I don't want users to think they did something wrong if the skin isn't changing immediately when they change the web files. If possible, I would like to get the cache to clear each time Zeppelin is restarted. If not, I will add a note to the README saying that adding the skin is only for aesthetic purposes so they shouldn't worry too much if they run into this issue.

**Comment by chrismattmann** [comment]
@MBoustani @BrianWilson1

**Comment by valeriearoth** [comment]
The solution is to press command + shift + r to reload the cache. I will update this on the README under possible pitfalls.

**Comment by MBoustani** [comment]
@chrismattmann @valeriearoth @BrianWilson1 
I was going to add html header meta to no-cach on any browser, but seems like it is already there.
Here is part of <head> code from a random notebook on scispark zeppelin source code:
` <meta http-equiv="cache-control" content="max-age=0"> <meta http-equiv="cache-control" content="no-cache"> <meta http-equiv="cache-control" content="no-store"> <meta http-equiv="expires" content="0"> <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT"> <meta http-equiv="pragma" content="no-cache"> 
`

**Comment by valeriearoth** [comment]
@chrismattmann @MBoustani @BrianWilson1 
Since we do want it to cache later on, what do you think about taking that part out and just making clearing the cache when you update the skin part of the requirements (instead of just a "possible pitfall")? It would be nice to have an explanation for this though.
